const {test}=require('node:test');
const assert=require('node:assert/strict');
const {createServer}=require('./index');
const {Client}=require('@modelcontextprotocol/sdk/client/index.js');
const {StreamableHTTPClientTransport}=require('@modelcontextprotocol/sdk/client/streamableHttp.js');

test('remote SDK pairing isolates clients, rejects invalid inputs, closes waits, and fences revoked keys',async t=>{
  const app=createServer({config:{agentEnabled:true},log(){}});
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
  t.after(()=>app.close());
  const url=`http://127.0.0.1:${app.server.address().port}/mcp`;
  let id=0;
  const dispatch=(socket,command,args={})=>app.service.dispatch(socket,command,{protocolVersion:2,requestId:`r${++id}`,...args});
  const a=dispatch('a','createRoom',{nickname:'A'}).snapshot;
  const b=dispatch('b','joinRoom',{roomId:a.roomId,nickname:'B'}).snapshot;
  const cmd=(socket,s,command)=>dispatch(socket,command,{roomId:s.roomId,generation:s.self.generation});
  const clients=await Promise.all([0,1].map(async i=>{ const client=new Client({name:`test-${i}`,version:'1'},{capabilities:{}}); await client.connect(new StreamableHTTPClientTransport(new URL(url))); t.after(()=>client.close()); return client; }));
  const call=async(i,name,args={})=>JSON.parse((await clients[i].callTool({name,arguments:args})).content[0].text);
  assert.equal((await clients[0].listTools()).tools.length,6);
  assert.equal((await call(1,'get_observation')).ok,false);
  const pairA=cmd('a',a,'createAgentPairing'), pairB=cmd('b',b,'createAgentPairing');
  const pa=await call(0,'connect_seat',{pairingCode:pairA.pairingCode});
  const pb=await call(1,'connect_seat',{pairingCode:pairB.pairingCode});
  assert(pa.ok);assert(pb.ok);assert.notEqual(pa.seatKey,pb.seatKey);
  assert.equal((await call(1,'connect_seat',{pairingCode:pairA.pairingCode})).code,'PAIRING_INVALID');
  assert.equal((await call(0,'get_observation',{seatKey:pa.seatKey})).observation.self.playerId,a.self.playerId);
  assert.equal((await call(1,'get_observation',{seatKey:pb.seatKey})).observation.self.playerId,b.self.playerId);
  assert.equal((await call(1,'get_observation',{seatKey:'invented'})).code,'INVALID_GRANT');
  assert.equal((await call(0,'get_observation',{seatKey:pa.seatKey,playerId:b.self.playerId})).code,'INVALID_REQUEST');
  cmd('a',a,'startGame');
  const obs=(await call(0,'get_observation',{seatKey:pa.seatKey})).observation;
  const current=obs.currentPlayerTurn===a.self.playerId?0:1;
  const key=current===0?pa.seatKey:pb.seatKey;
  const acting=(await call(current,'get_observation',{seatKey:key})).observation;
  const args={seatKey:key,requestId:'once',handId:acting.handId,turnId:acting.turnId,controlVersion:acting.self.controlVersion,action:'fold'};
  assert((await call(current,'act',args)).receipt.executed);
  assert((await call(current,'act',args)).receipt.executed);
  assert((await call(current,'get_action_status',{seatKey:key,requestId:'once'})).receipt.executed);
  const waitObs=(await call(0,'get_observation',{seatKey:pa.seatKey})).observation;
  const waiting=call(0,'wait_for_turn',{seatKey:pa.seatKey,revision:waitObs.revision});
  await new Promise(r=>setTimeout(r,40));
  cmd('a',a,'reclaimControl');
  assert.equal((await waiting).code,'INVALID_GRANT');
  assert.equal((await call(0,'get_action_status',{seatKey:pa.seatKey,requestId:'once'})).code,'INVALID_GRANT');
  assert((await call(1,'release_control',{seatKey:pb.seatKey})).ok);
  assert.equal((await call(1,'get_observation',{seatKey:pb.seatKey})).code,'INVALID_GRANT');
  assert.equal(app.service.agentListeners.size,0);
  assert.equal((await fetch(url,{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'})).status,403);
  assert.equal((await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload:'x'.repeat(9000)})})).status,413);
});

test('remote wait cancellation clears resources and pairing attempts are bounded',async t=>{
  const app=createServer({config:{agentEnabled:true},log(){}});
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r)); t.after(()=>app.close());
  const url=`http://127.0.0.1:${app.server.address().port}/mcp`;
  let id=0;
  const raw=(name,args,signal)=>fetch(url,{method:'POST',signal,headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:++id,method:'tools/call',params:{name,arguments:args}})});
  const read=async res=>JSON.parse((await res.json()).result.content[0].text);
  const created=app.service.dispatch('a','createRoom',{protocolVersion:2,requestId:'create',nickname:'A'}).snapshot;
  const pair=app.service.dispatch('a','createAgentPairing',{protocolVersion:2,requestId:'pair',roomId:created.roomId,generation:created.self.generation});
  const connected=await read(await raw('connect_seat',{pairingCode:pair.pairingCode}));
  const waitArgs={seatKey:connected.seatKey,revision:connected.observation.revision};
  const controller=new AbortController();
  const waiting=raw('wait_for_turn',waitArgs,controller.signal).catch(e=>e);
  for(let n=0;n<30 && app.service.agentListeners.size===0;n++)await new Promise(r=>setTimeout(r,10));
  assert.equal(app.service.agentListeners.size,1);
  assert.equal((await read(await raw('wait_for_turn',waitArgs))).code,'WAIT_IN_PROGRESS');
  controller.abort(); await waiting;
  for(let n=0;n<30 && app.service.agentListeners.size;n++)await new Promise(r=>setTimeout(r,10));
  assert.equal(app.service.agentListeners.size,0);
  for(let n=0;n<11;n++)assert.equal((await raw('connect_seat',{pairingCode:'0000-0000-0000-0000'})).status,200);
  assert.equal((await raw('connect_seat',{pairingCode:'0000-0000-0000-0000'})).status,429);
  app.service.setAgentEnabled(false);
  assert.equal((await raw('get_observation',{seatKey:connected.seatKey})).status,503);
});
