import { test, expect } from '@playwright/test'
async function enter(page) {
  await page.goto('/')
  await page.getByLabel('昵称').fill('观察者')
  await page.getByRole('button', { name: '观察练习', exact: true }).click()
  await expect(page.getByTestId('table-stage')).toHaveAttribute('data-players', '4')
}
async function progress(page) {
  const prompt = page.getByRole('button', { name: '跳过观察', exact: true })
  const fold = page.getByRole('button', { name: '弃牌', exact: true })
  const fast = page.getByRole('button', { name: '快速看完', exact: true })
  for (const control of [prompt, fold, fast]) {
    if (!await control.isVisible().catch(() => false)) continue
    try { await control.click({ timeout: 600 }); return }
    catch (error) { if (error.name !== 'TimeoutError') throw error } // A bot can finish the hand while the fast-forward button is being clicked.
  }
  await page.waitForTimeout(100)
}
test('完整 20 手练习、观察笔记、报告揭示与本地保存', async ({ page }) => {
  test.setTimeout(240000)
  await enter(page)
  await page.getByRole('button', { name: '暂停练习', exact: true }).click()
  await page.getByRole('button', { name: '观察 林舟', exact: true }).click()
  await page.getByLabel('你的判断').fill('目前证据不足，继续观察。')
  await page.getByRole('button', { name: '保存观察', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: '继续练习', exact: true })).toBeVisible({ timeout: 15000 })
  await page.getByRole('button', { name: '观察 林舟', exact: true }).click()
  await expect(page.getByLabel('你的判断')).toHaveValue('目前证据不足，继续观察。')
  await page.keyboard.press('Escape')
  await page.screenshot({ path: '/tmp/training-desktop.png', fullPage: true })
  await page.getByRole('button', { name: '继续练习', exact: true }).click()
  const heading=page.getByRole('heading', { name: '观察练习报告', exact: true })
  for(let i=0;i<2000&&!await heading.isVisible();i++) await progress(page)
  await expect(heading).toBeVisible()
  await expect(page.getByText(/完成 20 手/)).toBeVisible()
  await expect(page.getByText('报告已保存在此浏览器。')).toBeVisible()
  await expect(page.getByText('训练额外揭示', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: '揭示底牌与后续结果', exact: true }).click()
  await expect(page.getByText('训练额外揭示', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '返回首页', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: '查看练习报告', exact: true }).click()
  await page.getByRole('button', { name: '查看报告', exact: true }).click()
  await expect(heading).toBeVisible()
  await page.getByRole('button', { name: '返回首页', exact: true }).click()
  await page.getByRole('button', { name: '删除报告', exact: true }).click()
  await expect(page.getByText('暂无已保存报告。')).toBeVisible()
})
test('手机端关闭提示、暂停、笔记和提前结束报告', async ({ page }) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 390, height: 844 })
  await enter(page)
  await page.getByLabel('规则提示', { exact: true }).uncheck()
  await expect(page.getByText('规则与观察提示', { exact: true })).not.toBeVisible()
  for(let i=0;i<400&&!await page.getByRole('heading', { name: /观察练习 · [1-9]/ }).isVisible();i++) await progress(page)
  await page.getByRole('button', { name: '暂停练习', exact: true }).click()
  await page.getByRole('button', { name: '观察 苏禾', exact: true }).click()
  await page.getByLabel('你的判断').fill('先区分强制盲注与主动入池。')
  await page.getByRole('checkbox', { name: '第 1 手', exact: true }).check()
  await page.getByRole('button', { name: '保存观察', exact: true }).click()
  await page.screenshot({ path: '/tmp/training-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: '结束练习', exact: true }).click()
  await page.getByRole('button', { name: '确认结束', exact: true }).click()
  for(let i=0;i<400&&!await page.getByRole('heading', { name: '观察练习报告', exact: true }).isVisible();i++) await progress(page)
  await expect(page.getByRole('heading', { name: '观察练习报告', exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/training-report-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
